1/ To generate html file from md, run the command:

$ pandoc -s Usermanual.md -o file_name.html --metadata title="Custom title for html file" --css=github-markdown.css

for example:

$ pandoc -s Usermanual.md -o User_Manual_30_SEP_2024.html --metadata title="User Manual for Jungfrau GUI" --css=github-markdown.css



2/ To view the html file, run the command, e.g. for Firefox:

$ firefox file_name.html &

or for Chrome: 

google-chrome file_name.html &



